import fs from 'node:fs';
import { join } from 'node:path';

import {
  createWebpackConfig,
  resolveImaConfig,
  ImaCliArgs,
  compileLanguages,
  runImaPluginsHook,
} from '@ima/cli';
import type { GlobalImaObject } from '@ima/core';
import { logger } from '@ima/dev-utils/logger';
import { Options } from '@storybook/core-webpack';
import chalk from 'chalk';
import { Configuration } from 'webpack';

import {
  resolveStyles,
  resolveAliases,
  resolveLanguageEntryPoints,
  resolveSWC,
  resolveRevivalSettings,
} from './presets/resolvers.js';

export const webpackFinal = async (
  config: Configuration,
  options: Options & { $IMA: GlobalImaObject; skipPlugins?: string[] }
): Promise<Configuration> => {
  const mockArgs: ImaCliArgs = {
    clean: false,
    environment:
      process.env.NODE_ENV === 'production' ? 'production' : 'development',
    rootDir: process.cwd(),
    command: options.configType === 'DEVELOPMENT' ? 'dev' : 'build',
  };

  // Clear IMA build folder - it might contain obsolete files generated by plugins
  const buildFolder = join(mockArgs.rootDir, 'build');
  logger.write(
    `${chalk.green('info')} => Removing build folder '${buildFolder}'`
  );

  fs.rmSync(buildFolder, { recursive: true, force: true });

  const imaConfig = await resolveImaConfig(mockArgs);

  // Remove chosen CLI plugins from build (some plugins might not be compatible with storybook)
  const { skipPlugins = [] } = options;
  if (skipPlugins.length) {
    logger.write(
      `${chalk.green('info')} => Configured to skip CLI plugins: ${skipPlugins
        .map(pluginName => chalk.blue(pluginName))
        .join(', ')}`
    );
    imaConfig.plugins = (imaConfig?.plugins || []).filter(
      plugin => !skipPlugins.includes(plugin.constructor.name)
    );
  }
  await runImaPluginsHook(mockArgs, imaConfig, 'preProcess');
  const imaWebpackConfig = await createWebpackConfig(mockArgs, imaConfig);
  const clientConfig = imaWebpackConfig.find(c => c.name === 'client.es');

  if (!clientConfig) {
    throw Error(
      '@ima/storybook-integration: Unable to resolve client webpack config.'
    );
  }

  // Compile languages
  // @ts-expect-error missing in types
  await compileLanguages(imaConfig, mockArgs.rootDir, options._name === 'dev');

  // Replace minimizers
  config.optimization = {
    ...clientConfig.optimization,
    minimizer: clientConfig.optimization?.minimizer ?? [],
  };

  // Update storybook config with ima specifics
  return [
    resolveLanguageEntryPoints,
    resolveAliases,
    resolveStyles,
    resolveSWC,
    resolveRevivalSettings,
  ].reduce((acc, resolver) => {
    acc = resolver({
      config,
      imaConfig,
      imaWebpackConfig: clientConfig as Configuration,
      args: mockArgs,
      options,
    });

    return acc;
  }, config);
};
