import fs from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  createViteConfig,
  resolveImaConfig,
  resolveEnvironment,
  ImaCliArgs,
  runImaPluginsHook,
  VIRTUAL_LOCALE_PREFIX,
} from '@ima/cli';
import type { GlobalImaObject } from '@ima/core';
import { logger } from '@ima/dev-utils/logger';
import chalk from 'chalk';
import type { PreviewAnnotation } from 'storybook/internal/types';
import { mergeConfig, type UserConfig, type Plugin } from 'vite';

export type ViteFinalOptions = {
  configType?: 'DEVELOPMENT' | 'PRODUCTION';
  $IMA?: GlobalImaObject;
  skipPlugins?: string[];
  language?: string;
  https?: boolean;
  host?: string;
  port?: number;
};

/**
 * Resolves the IMA CLI args used for both viteFinal and previewAnnotations.
 */
function makeCliArgs(configType?: 'DEVELOPMENT' | 'PRODUCTION'): ImaCliArgs {
  return {
    clean: false,
    environment:
      process.env.NODE_ENV === 'production' ? 'production' : 'development',
    rootDir: process.cwd(),
    command: configType === 'DEVELOPMENT' ? 'dev' : 'build',
  };
}

/**
 * Resolves the language to use for the Storybook session.
 * Prefers the explicit `language` option, falls back to the first language
 * defined in imaConfig, then 'en'.
 */
function resolveLanguage(
  imaConfig: Awaited<ReturnType<typeof resolveImaConfig>>,
  options: Pick<ViteFinalOptions, 'language'>
): string {
  return options.language ?? Object.keys(imaConfig.languages ?? {})[0] ?? 'en';
}

/**
 * Creates a Vite plugin that injects mocked $IMA revival settings into the
 * HTML document before any application scripts run.
 */
function createRevivalSettingsPlugin(
  options: ViteFinalOptions,
  rootDir: string,
  language: string
): Plugin {
  // Load env using regression environment so $App.$Debug etc. are available
  const oldEnv = process.env.NODE_ENV;
  process.env.NODE_ENV = 'regression';
  const env = resolveEnvironment(rootDir);
  process.env.NODE_ENV = oldEnv;

  const revivalSettings = `(function (root) {
    root.$Debug = ${env.$App?.$Debug};
    root.$IMA = root.$IMA || {};
    $IMA.Test = true;
    $IMA.SPA = true;
    $IMA.$App = ${JSON.stringify(env.$App || {})};
    $IMA.$PublicPath = "";
    $IMA.$RequestID = "storybook-request-id";
    $IMA.$Language = "${language}";
    $IMA.$Env = "regression";
    $IMA.$Debug = ${env.$App?.$Debug};
    $IMA.$Version = "${env.$Version}";
    $IMA.$Protocol = "${options.https ? 'https:' : 'http:'}";
    $IMA.$Host = "${options.host ? options.host : `localhost:${options.port ?? 6006}`}";
    $IMA.$Path = "";
    $IMA.$Root = "";
    $IMA.$LanguagePartPath = "";
  })(typeof window !== 'undefined' && window !== null ? window : global);
`;

  return {
    name: 'ima-storybook-revival-settings',
    transformIndexHtml: {
      order: 'pre',
      handler() {
        return [
          {
            tag: 'script',
            attrs: { type: 'text/javascript' },
            children: revivalSettings,
            injectTo: 'head-prepend',
          },
        ];
      },
    },
  };
}

export const viteFinal = async (
  config: UserConfig,
  options: ViteFinalOptions
): Promise<UserConfig> => {
  const mockArgs = makeCliArgs(options.configType);

  // Clear IMA build folder — it might contain obsolete files generated by plugins
  const buildFolder = join(mockArgs.rootDir, 'build');
  logger.write(
    `${chalk.green('info')} => Removing build folder '${buildFolder}'`
  );
  fs.rmSync(buildFolder, { recursive: true, force: true });

  const imaConfig = await resolveImaConfig(mockArgs);

  // Remove chosen CLI plugins from build (some plugins might not be compatible with storybook)
  const { skipPlugins = [] } = options;
  if (skipPlugins.length) {
    logger.write(
      `${chalk.green('info')} => Configured to skip CLI plugins: ${skipPlugins
        .map(pluginName => chalk.blue(pluginName))
        .join(', ')}`
    );
    imaConfig.plugins = (imaConfig?.plugins || []).filter(
      plugin => !skipPlugins.includes(plugin.constructor.name)
    );
  }

  await runImaPluginsHook(mockArgs, imaConfig, 'preProcess');
  const imaViteConfig = await createViteConfig(mockArgs, imaConfig);

  const language = resolveLanguage(imaConfig, options);

  // Build merged config:
  // - Take resolve.alias and css settings from the IMA Vite config
  // - Append IMA plugins (language virtual modules, etc.) to Storybook plugins
  // - Inject $IMA revival settings via transformIndexHtml
  // - Merge define (global: 'globalThis')
  // - Storybook manages its own server/build options, so we only forward
  //   the subset relevant to application code resolution.
  const imaSubset: UserConfig = {
    resolve: {
      alias: imaViteConfig.resolve?.alias,
      extensions: imaViteConfig.resolve?.extensions,
    },
    css: imaViteConfig.css,
    define: imaViteConfig.define,
    plugins: [
      ...(imaViteConfig.plugins ?? []),
      createRevivalSettingsPlugin(options, mockArgs.rootDir, language),
    ],
  };

  return mergeConfig(config, imaSubset);
};

/**
 * Register the integration's preview entry (loaders, decorators, argTypes)
 * and the locale virtual module so Storybook automatically composes them into
 * projectAnnotations without requiring users to manually import anything in
 * their preview.js.
 *
 * The locale virtual module is registered as a bare annotation so that
 * Storybook's builder-vite generates a static `import` for it in the virtual
 * project-annotations entry — this is the idiomatic way to pull a virtual
 * module into Storybook's bundle without patching other files.
 */
export const previewAnnotations = async (
  input: string[] = [],
  options: ViteFinalOptions
): Promise<PreviewAnnotation[]> => {
  const mockArgs = makeCliArgs(options.configType);
  const imaConfig = await resolveImaConfig(mockArgs);
  const language = resolveLanguage(imaConfig, options);

  return [
    ...input,
    fileURLToPath(new URL('./preview.js', import.meta.url)),
    // Bare virtual module ID — processPreviewAnnotation passes it through as-is
    // so Storybook generates: import * as _locale from 'virtual:ima-locale/cs'
    { bare: `${VIRTUAL_LOCALE_PREFIX}${language}`, absolute: '' },
  ];
};
